import React, { ReactNode } from 'react';
import './style.less';
export interface LayoutProps {
    headerExtra?: ReactNode;
    logo?: ReactNode;
    title?: ReactNode;
    headerTheme?: 'dark' | 'default';
    headerHeight?: number;
    sideMaxWidth?: number;
    sideMinWidth?: number;
    sideCollapsed?: boolean;
    showSearchMenu?: boolean;
    searchMenuPlaceholder?: string;
    collectedMenuTitle?: string;
    renderSide?: () => void;
    showSide?: boolean;
    sideTheme?: 'dark' | 'default';
    logoTheme?: 'dark' | 'default';
    showHeader?: boolean;
    showHeaderSideToggle?: boolean;
    showPageHeader?: boolean;
    pageHeaderHeight?: number;
    menus?: [];
    collectedMenus?: [];
    onMenuCollect?: () => void;
    keepMenuOpen?: boolean;
    layoutType?: string;
    keepPageAlive?: boolean;
    showTab?: boolean;
    persistTab?: boolean;
    tabHeight?: number;
    showTabHeaderExtra?: boolean;
    showTabSideToggle?: boolean;
    hashRouter?: boolean;
    baseName?: string;
    className?: ReactNode;
    routes?: [];
    render404?: () => ReactNode;
}
declare const Layout: React.ForwardRefExoticComponent<LayoutProps & React.RefAttributes<any>>;
export default Layout;
